# Usage: python tests/make_fake_library.py ; set CALIBRE_LIBRARY=tests\Calibre Library ; python calibre_mcp.py --sync ; python tests/smoke_test.py
import sys, json; sys.argv=['x']; sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parents[1]))
import calibre_mcp as m
from pathlib import Path
m.LIB = m.Library(m.detect_library(), m.default_data_dir())
def show(name, **kw):
    try: r = getattr(m, name)(**kw); print(f"== {name} {kw}\n", json.dumps(r, ensure_ascii=False)[:900])
    except Exception as e: print(f"== {name} {kw} -> ERR {type(e).__name__}: {e}")
show("calibre_search_books", q="security")
show("calibre_search_books", author="honig", sort="added", descending=True)
show("calibre_search_books", language="ita", min_rating=None, has_annotations=True)
show("calibre_search_fulltext", query="firewall")
show("calibre_search_fulltext", query="securite ecole", mode="phrase", snippet_chars=120)
show("calibre_search_fulltext", query="segment*", tag="networking")
show("calibre_search_fulltext", query='firewall NEAR(difesa, 5)', mode="raw")
show("calibre_search_fulltext", query='"unterminated', mode="raw")
show("calibre_search_fulltext", query='firewall OR NOT x', mode="all")
show("calibre_get_book", book_id=1)
show("calibre_get_book", book_id=2)
r = m.calibre_search_fulltext(query="segmentazione")
off = r["results"][0]["snippets"][0]["offset"]
show("calibre_read_text", book_id=1, offset=off, max_chars=300, center=True)
show("calibre_find_in_book", book_id=1, query="firewall", context_chars=100)
show("calibre_get_toc", book_id=1)
show("calibre_read_section", book_id=1, section=1)
show("calibre_get_toc", book_id=2)
show("calibre_read_section", book_id=2, start_page=2, end_page=3)
show("calibre_read_text", book_id=2, max_chars=300)
show("calibre_find_in_book", book_id=2, query="process hollowing", phrase=True, context_chars=100)
show("calibre_list_facets", kind="tags")
show("calibre_list_facets", kind="formats")
show("calibre_get_annotations", query="firewall")
show("calibre_read_section", book_id=1, section=9)
